version: '2.0'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: osb/docker-airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
#       user: "${MYUID}:${MYGID}"
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/airflow/dags:/usr/local/airflow/dags
            - /home/airflow/hades:/usr/local/hades
            - /home/airflow/input:/usr/local/input
            - /home/airflow/output:/usr/local/output
            - /home/airflow/working:/usr/local/working
            - /home/airflow/script:/usr/local/script
            - /home/airflow/plugins:/usr/local/airflow/plugins

        ports:
            - "8080:8080"
        command: webserver
#        healthcheck:
#            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
#            interval: 30s
#            timeout: 30s
#            retries: 3

#    vault:
#        image: vault
#        container_name: vault-airflow
#        ports:
#            - "8200:8200"
#        restart: always
#        volumes:
#            - /home/airflow/volumes/logs:/vault/logs
#            - /home/airflow/volumes/file:/vault/file
#            - /home/airflow/volumes/config:/vault/config
#        cap_add:
#            - IPC_LOCK
#        entrypoint: vault server -config=/vault/config/vault.json
